server:
    port: 1100

spring:
    application:
        name: search-service

eureka:
    instance:
        prefer-ip-address: true
    client:
        register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
        fetch-registry: true
        serviceUrl:
            defaultZone: http://localhost:1000/eureka/

management:
    endpoints:
        web:
            exposure:
                include: "*"